providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
    "mkdir -p /opt/venv",
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt",
    "npm install",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "/opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300"