[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["pip install -r requirements.txt", "cd frontend && npm install && cd .."]

[phases.build]
cmds = ["cd frontend && npm run build && cd .."]

[start]
cmd = "gunicorn app_modified:app --bind 0.0.0.0:$PORT" 