# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "nodejs_18", "gcc"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -r requirements.txt",
    "cd frontend && npm install && npm run build && cd ..",
    "cp -r frontend/dist/* static/ || true"
]

[start]
cmd = "gunicorn app_simple:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"