[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
    "pip install flask flask-cors boto3 gunicorn python-dotenv",
    "cd frontend && npm install && cd .."
]

[phases.build]
cmds = [
    "cd frontend && npm run build && cd .."
]

[start]
cmd = "gunicorn app_simple:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120" 