[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[providers]
python = "python311"

[phases.install]
cmds = [
    "python -m venv venv",
    ". venv/bin/activate && pip install -r requirements.txt",
    "npm install"
]

[phases.build] 
cmds = ["cd frontend && npm install && npm run build"]

[start]
cmd = ". venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"