[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd frontend && npm install && npm run build && cd .. && mkdir -p static && cp -r frontend/dist/* static/"]

[start]
cmd = "python app_simple.py"