# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "nodejs_18", "gcc", "libffi", "openssl"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt",
    "npm --prefix frontend install",
    "npm --prefix frontend run build",
    "mkdir -p static",
    "cp -r frontend/dist/* static/ || echo 'No dist files to copy yet'"
]

[start]
cmd = "gunicorn app_simple:app --bind 0.0.0.0:$PORT --timeout 120"