[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "gcc"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "npm install",
    "cd frontend && npm install && cd .."
]

[phases.build]
cmds = [
    "cd frontend && npm run build && cd .."
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300"