[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "gcc"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install && npm run build && cd .."
]

[start]
cmd = "gunicorn app_simple:app"